SELECT * FROM TargetData

SELECT * FROM SourceData


BEGIN TRAN

MERGE INTO TargetData AS tgt
USING SourceData AS src
	ON tgt.Id = src.Id
WHEN NOT MATCHED BY SOURCE AND tgt.SomeDate = '20170203'
 THEN UPDATE
	SET tgt.Data = tgt.Data + 'tyi'
WHEN NOT MATCHED BY SOURCE  THEN DELETE
;



SELECT * FROM TargetData


ROLLBACK TRAN;